
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/secretgraph"
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data

  app:
    build: .
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: secretgraph
    stdin_open: true
    tty: true
    # ports:
    #   - "8000:8000"

volumes:
  neo4j_data:
