services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/secretgraph
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - ./import:/import
