version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/secretgraph
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data

  app:
    build: .
    depends_on:
      - neo4j
    # Environment variables can be passed to your Python app if needed.
    # For example, use the service name "neo4j" as the host when connecting:
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: secretgraph
    # If your app exposes a port (e.g., if it runs a web server), uncomment and adjust the following:
    # ports:
    #   - "8000:8000"

volumes:
  neo4j_data:
